/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#e5e2e1",
        "primary-fixed": "#003554",
        "on-surface": "#003554",
        "on-primary": "#ffffff",
        "on-background": "#003554",
        "surface-bone": "#F1F5F9",
        "primary-container": "#003554",
        "inverse-on-surface": "#f9f0dd",
        "background": "#F1F5F9",
        "surface-dim": "#e2e8f0",
        "primary": "#003554",
        "on-tertiary-fixed-variant": "#004f54",
        "surface": "#F1F5F9",
        "inverse-surface": "#343024",
        "inverse-primary": "#003554",
        "on-tertiary-fixed": "#002022",
        "on-primary-container": "#ffffff",
        "tertiary-fixed-dim": "#006494",
        "tech-gray-dark": "#003554",
        "stark-white": "#ffffff",
        "error": "#ba1a1a",
        "outline-muted": "#475569",
        "secondary-fixed-dim": "#c8c6c5",
        "industrial-yellow": "#006494",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e8f0",
        "on-secondary-container": "#475569",
        "surface-container-low": "#f8fafc",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#475569",
        "outline": "#475569",
        "secondary-container": "#e2dfde",
        "surface-tint": "#003554",
        "surface-container-high": "#cbd5e1",
        "tertiary": "#006494",
        "surface-container": "#f1f5f9",
        "outline-variant": "#475569",
        "on-primary-fixed": "#ffffff",
        "on-tertiary-container": "#006494",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003554",
        "tertiary-fixed": "#006494",
        "hazard-red": "#ff3b30",
        "surface-container-highest": "#94a3b8",
        "primary-fixed-dim": "#003554",
        "on-secondary-fixed": "#1c1b1b",
        "secondary": "#475569",
        "tertiary-container": "#006494",
        "surface-bright": "#F1F5F9",
        "on-surface-variant": "#475569"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "container-max": "1600px",
        "section-padding": "64px",
        "margin-mobile": "16px",
        "unit": "8px"
      },
      "fontFamily": {
        "headline-xl": ["Outfit", "sans-serif"],
        "status-code": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "label-caps": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "price-display": ["Outfit", "sans-serif"],
        "serif": ["Outfit", "sans-serif"]
      },
      "fontSize": {
        "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "status-code": ["10px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "price-display": ["24px", {"lineHeight": "1", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
